### ISSUE TITLE
Оптимізувати простір головної сторінки

### ISSUE THREAD

**Issue by anxolerd** [KPI-FICT-IP32/Blog#21]
## Мета

Оптимізувати простір головної сторінки. Зробити процес знаходження потрібної лекції швидшим.
## Проблема

Наразі у блозі є лише лекції з двох дисциплін, але вони вже не вміщаються на одному екрані. При додаванні нових дисциплін посилань на сторінці ставатиме все більше, знайти що-небудь на ній займатиме більше часу (скроллінг).

![image](https://cloud.githubusercontent.com/assets/6533582/16713377/60fb6bc4-46ae-11e6-8a54-beecf83eff1a.png)

_ Зверніть увагу на смугу прокрутки біля правого краю знімку екрану_

Також при надто великій кількості дописів можуть початися проблеми зі швидкодією, так як браузеру може стати дуже кепсько від такого широкого дерева DOM.
## Пропозиції
1. Заховати список дописів по дисципліні під спойлер
   ![ezgif-3771391124](https://cloud.githubusercontent.com/assets/6533582/16713446/b08308c6-46b0-11e6-917f-567f5ed3beb2.gif)
   Це дозволить позбутися від "простирадла" посилань на головній сторінці та, можливо, пришвидшить пошук потрібної лекції
2. Винести посилання в рамках категорій на окремі сторінки. На головній сторінці залишити лише посилання на сторінки категорій. Вирішує проблему пошуку потрібного посилання серед купи подібних та проблему навантаження на браузер. Проте він вимагає дослідження -- як зробити так, щоб сторінки категорій не треба було створювати ручками для кожної категорії.
3. Додати пагінацію. 
   ![image](https://cloud.githubusercontent.com/assets/6533582/16713474/4ab8f928-46b1-11e6-8b6e-31116624acca.png)
   Це дозволить зменшити навантаження на браузер. Jekyll [вміє робити пагінацію із коробки](https://jekyllrb.com/docs/pagination/), але в нашому випадку, скоріш за все, її доведеться дороблювати напильником.

**Comment by anxolerd** [comment]
@KPI-FICT-IP32/everybody Що скажете?

**Comment by ValkoVolodya** [comment]
Хороша ідея. Особливо перший пункт зробить сторінку красивішою в рази.

**Comment by anxolerd** [comment]
Resolved by introducing Sphinx
